blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Junior-Reactive-Solutions/eat-good-uganda/tree/master/docs
    about: Read the project documentation
  - name: Discussions
    url: https://github.com/Junior-Reactive-Solutions/eat-good-uganda/discussions
    about: Ask questions and share ideas
